In [1]:
import pandas as pd
import numpy as np
import random
import datetime
from sys import getsizeof

In [2]:
list1 = [21,31,42,32,43,45]
list2 = [21,433,54,31,76,44]

# Operations On Lists

In [3]:
list1+list2

[21, 31, 42, 32, 43, 45, 21, 433, 54, 31, 76, 44]

In [4]:
sum = []
for i in range(0, len(list1)):
    sum.append(list1[i]+list2[i])
print(sum)

[42, 464, 96, 63, 119, 89]


In [5]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [6]:
arr1+arr2

array([ 42, 464,  96,  63, 119,  89])

## Complexity of Addition Operation reduces using numpy

In [7]:
np.append(arr1, arr2)

array([ 21,  31,  42,  32,  43,  45,  21, 433,  54,  31,  76,  44])

### Now, comparing time required for completion of Division for a large values

In [19]:
#Generating a random list of 1000 entries
list3 = []
list4 = []
for i in range(0, 10000000):
    list3.append(random.randint(10000, 20000))
    list4.append(random.randint(10000,20000))
start = datetime.datetime.now()
ans = []
for x in range(0, len(list3)):
    ans.append(list3[1]/list4[i])
end = datetime.datetime.now()
print(end - start)

0:00:06.830558


In [20]:
#Calculating quotient for numpy
arr1 = np.array(list3)
arr2 = np.array(list4)
start = datetime.datetime.now()
res = np.array(arr1/arr2)
end = datetime.datetime.now()
print(end - start)

0:00:00.294197


### Comparing memory size for list and numpy array

In [22]:
print(getsizeof(ans))
print(getsizeof(res))

81528056
80000096


#### We can thus see that numpy uses less memory thereby optimizing memory utilisation

In [23]:
np_2d = np.array([list1, list2])
print(np_2d[0:5, 0:5])
df = pd.read_csv('headbrain.csv')
print(df.head(5))

[[ 21  31  42  32  43]
 [ 21 433  54  31  76]]
   head.size  brain.weight gender age.group
0       4512          1530   male     20-46
1       3738          1297   male     20-46
2       4261          1335   male     20-46
3       3777          1282   male     20-46
4       4177          1590   male     20-46


#### Lets create numpy array of heterogeneous data types

In [24]:
np_array = np.array([[12,43,56,74,53,28], ['hello', 'there', 'this', 'is', 'a', 'numpy', '2D', 'array']])
np_array

array([list([12, 43, 56, 74, 53, 28]),
       list(['hello', 'there', 'this', 'is', 'a', 'numpy', '2D', 'array'])],
      dtype=object)

In [25]:
print(df.dtypes)

head.size        int64
brain.weight     int64
gender          object
age.group       object
dtype: object


## numpy converts all elements into homogeneous data type implicitly while pandas does not